### ISSUE TITLE
Button to navigate on columns is not visible

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#1035]

**Comment by Dominik-Weinzierl** [comment]
I think the issue is already resolved as it only occurs in the hosted scrumlr version, not in our main branch 🤔 (tested with Chrome where this problem occurs)

Main:

https://user-images.githubusercontent.com/60005702/141765524-9dc31034-82a1-445a-862d-f39194d2c1f5.mov

Hosted:

https://user-images.githubusercontent.com/60005702/141765540-36fcacb1-89e1-417d-99da-dec167cba416.mov

**Comment by Dominik-Weinzierl** [comment]
Update:
Seems like these values aren't right, but they should 🤔 

`board__navigation`:   
- `local`: opacity: 50%;
- `hosted`: opacity: 1%;

`board__navigation:hover`: 
- `local`: opacity: 100%; 
- `hosted`: opacity: 1%;
