### ISSUE TITLE
Add analytics tooling

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#164]

**Comment by brandstetterm** [comment]
I've had a quick look on some available options we could use. Maybe we could use https://matomo.org/ for our case since it attaches great importance on data protection and customer privacy. Also, there's the Matomo On-Premise option to self-host on our own servers so we can ensure that the data remains in our hand. Doesn't sound bad overall I'd say

**Comment by Lennart01** [comment]
https://github.com/umami-software/umami might also be an option to look into.
What type of analytics are we interested in?
Do we want session tracking or just simple usage stats?
