### ISSUE TITLE
Add request retry mechanism for client-side resilience

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#240]
As a user my requests should be retried if I had connection problems which lead to request failures.

AC:
- Requests with client side errors (e.g. Timeout, Connection losses, ...) should be retried in intervals until they succeed

**Comment by brandstetterm** [comment]
According to [this StackOverflow thread](https://stackoverflow.com/questions/30823754/how-to-respond-an-error-in-a-parse-cloud-function-and-prevent-retries), Parse is retrying failed requests due to network connectivity or server availability issues itself. Unfortunately this has not been documented anywhere (as always).  

I've tried to add a note with a non-running backend and the failed request has been resend 4 times in a period of ~ 2 seconds.

What do you think about that @bitionaire?
