### ISSUE TITLE
As a user/company I want all sensitive data to be encrypted

### ISSUE THREAD

**Issue by bitionaire** [inovex/scrumlr.io#242]
As a user/company I want all sensitive data to be also encrypted within the database.

AC:
- Add asymmetric & secure key-exchange on boards
- Encrypt sensitive data by a secure key (e.g. note texts, board & column names)

**Comment by brandstetterm** [comment]
I think we should further refine this task because atm I don't know 100% what has to be done to complete this task. 

Thoughts: 
- The server has to create a fresh public/private key pair for every board
- Every board session/participant has to create its own public/private key pair 
- I guess we should only use asymmetric encryption to share a symmetric key and all the sensitive information will be symmetrically encrypted with the symmetric key (one reason for that would be computing costs for example)
- A symmetric encryption key will be sent to every board session (encrypted asymmetrically) 
- All sensitive data will be symmetrically encrypted with the symmetric encryption key

Questions: 
- Where does the participant store its private key? 
- Is a participant required to enter his private key upon re-joining the board? 
- Where will the public/private key pair of a board be saved securely? 
- Where are we going to save the symmetric key securely?
- Are we (developers with access to the database) allowed to see the asymmetric key pair or symmetric key and therefore the plaintext of the encrypted data? 
- What is sensitive information? (besides the obvious like notes, participants, board title, etc.)
