### ISSUE TITLE
Revise icons

### ISSUE THREAD

**Issue by SelinaBuff** [inovex/scrumlr.io#3268]
**User Stories:**

> 1. As a user, I expect the icons to consistently maintain the same style. This requires a reevaluation of the icon library in the code base. This ensures a cohesive design and a user-friendly language. It enhances recognizability and forms a unified and harmonious interface.
> 
> 2. As a user, I anticipate that the icons will be tailored for both the dark and light modes to provide a seamless user experience in either setting.

**You can find the Design on Figma. Go on the left menu on "🎨 Style Guide" and then to the section "Icons":**
![Image](https://github.com/inovex/scrumlr.io/assets/116653219/c818cebe-2c94-41cd-8473-d5ffbf73ca4a)

**or download the icons here:**
[Scrumlr_Icons_09062023.zip](https://github.com/inovex/scrumlr.io/files/12301050/Scrumlr_Icons_09062023.zip)

**Comment by blxckOxymoron** [comment]
I've started implementing this and created a list of icons that don't have an "updated" version:

- company icons (apple, github, google, microsoft, inovex)
- some feedback icons: `icon-bug`, `icon-praise` (could maybe be replaced with `add-emoji`)
<img src="https://raw.githubusercontent.com/inovex/scrumlr.io/63ed5e6bb4702268a9cdd4a47da0f13d5c983770/src/assets/icon-bug.svg" width="64" height="64"></img>
<img src="https://raw.githubusercontent.com/inovex/scrumlr.io/63ed5e6bb4702268a9cdd4a47da0f13d5c983770/src/assets/icon-praise.svg" width="64" height="64"></img>
-  `icon-clipboard` (could maybe be replaced with `duplicate`)
<img src="https://raw.githubusercontent.com/inovex/scrumlr.io/63ed5e6bb4702268a9cdd4a47da0f13d5c983770/src/assets/icon-clipboard.svg" width="64" height="64"></img>
- the icons for the timer 
they could be replaced with html, since they are only numbers or +/- with circles around them
<img src="https://raw.githubusercontent.com/inovex/scrumlr.io/63ed5e6bb4702268a9cdd4a47da0f13d5c983770/src/assets/icon-plus.svg" width="64" height="64"></img>
- the icons for adding and removing participants:
<img src="https://raw.githubusercontent.com/inovex/scrumlr.io/63ed5e6bb4702268a9cdd4a47da0f13d5c983770/src/assets/icon-join.svg" width="64" height="64"></img> (this is in figma already, but I unfortunately wasn't able to export it)
<img src="https://raw.githubusercontent.com/inovex/scrumlr.io/63ed5e6bb4702268a9cdd4a47da0f13d5c983770/src/assets/icon-kick-participant.svg" width="64" height="64"></img>
- the `logout` icon
<img src="https://raw.githubusercontent.com/inovex/scrumlr.io/63ed5e6bb4702268a9cdd4a47da0f13d5c983770/src/assets/icon-logout.svg" width="64" height="64"></img>
- the `menu` icon used in the menu bar on mobile
<img src="https://raw.githubusercontent.com/inovex/scrumlr.io/63ed5e6bb4702268a9cdd4a47da0f13d5c983770/src/assets/icon-menu.svg" width="64" height="64"></img>
- the `print` icon 
<img src="https://raw.githubusercontent.com/inovex/scrumlr.io/63ed5e6bb4702268a9cdd4a47da0f13d5c983770/src/assets/icon-print.svg" width="64" height="64"></img>
- the `refresh` icon
<img src="https://raw.githubusercontent.com/inovex/scrumlr.io/63ed5e6bb4702268a9cdd4a47da0f13d5c983770/src/assets/icon-refresh.svg" width="64" height="64"></img>
- the `remove` (-) icon 
<img src="https://raw.githubusercontent.com/inovex/scrumlr.io/63ed5e6bb4702268a9cdd4a47da0f13d5c983770/src/assets/icon-remove.svg" width="64" height="64"></img>
- the `warning` icon
<img src="https://raw.githubusercontent.com/inovex/scrumlr.io/63ed5e6bb4702268a9cdd4a47da0f13d5c983770/src/assets/icon-warning.svg" width="64" height="64"></img>

I'll keep the old icons around for now, maybe with some small internal modifications so they can be updated easily later.

One thing I'd like to note, too, is that I found the name `open.svg` for the globe icon somewhat confusing

**Comment by brandstetterm** [comment]
> I've started implementing this and created a list of icons that don't have an "updated" version:
> 
>     * company icons (apple, github, google, microsoft, inovex)
> 
>     * some feedback icons: `icon-bug`, `icon-praise` (could maybe be replaced with `add-emoji`)
>       <img alt="" width="64" height="64" src="https://raw.githubusercontent.com/inovex/scrumlr.io/63ed5e6bb4702268a9cdd4a47da0f13d5c983770/src/assets/icon-bug.svg">
>       <img alt="" width="64" height="64" src="https://raw.githubusercontent.com/inovex/scrumlr.io/63ed5e6bb4702268a9cdd4a47da0f13d5c983770/src/assets/icon-praise.svg">
> 
>     * `icon-clipboard` (could maybe be replaced with `duplicate`)
>       <img alt="" width="64" height="64" src="https://raw.githubusercontent.com/inovex/scrumlr.io/63ed5e6bb4702268a9cdd4a47da0f13d5c983770/src/assets/icon-clipboard.svg">
> 
>     * the icons for the timer
>       they could be replaced with html, since they are only numbers or +/- with circles around them
>       <img alt="" width="64" height="64" src="https://raw.githubusercontent.com/inovex/scrumlr.io/63ed5e6bb4702268a9cdd4a47da0f13d5c983770/src/assets/icon-plus.svg">
> 
>     * the icons for adding and removing participants:
>       <img alt="" width="64" height="64" src="https://raw.githubusercontent.com/inovex/scrumlr.io/63ed5e6bb4702268a9cdd4a47da0f13d5c983770/src/assets/icon-join.svg"> (this is in figma already, but I unfortunately wasn't able to export it)
>       <img alt="" width="64" height="64" src="https://raw.githubusercontent.com/inovex/scrumlr.io/63ed5e6bb4702268a9cdd4a47da0f13d5c983770/src/assets/icon-kick-participant.svg">
> 
>     * the `logout` icon
>       <img alt="" width="64" height="64" src="https://raw.githubusercontent.com/inovex/scrumlr.io/63ed5e6bb4702268a9cdd4a47da0f13d5c983770/src/assets/icon-logout.svg">
> 
>     * the `menu` icon used in the menu bar on mobile
>       <img alt="" width="64" height="64" src="https://raw.githubusercontent.com/inovex/scrumlr.io/63ed5e6bb4702268a9cdd4a47da0f13d5c983770/src/assets/icon-menu.svg">
> 
>     * the `print` icon
>       <img alt="" width="64" height="64" src="https://raw.githubusercontent.com/inovex/scrumlr.io/63ed5e6bb4702268a9cdd4a47da0f13d5c983770/src/assets/icon-print.svg">
> 
>     * the `refresh` icon
>       <img alt="" width="64" height="64" src="https://raw.githubusercontent.com/inovex/scrumlr.io/63ed5e6bb4702268a9cdd4a47da0f13d5c983770/src/assets/icon-refresh.svg">
> 
>     * the `remove` (-) icon
>       <img alt="" width="64" height="64" src="https://raw.githubusercontent.com/inovex/scrumlr.io/63ed5e6bb4702268a9cdd4a47da0f13d5c983770/src/assets/icon-remove.svg">
> 
>     * the `warning` icon
>       <img alt="" width="64" height="64" src="https://raw.githubusercontent.com/inovex/scrumlr.io/63ed5e6bb4702268a9cdd4a47da0f13d5c983770/src/assets/icon-warning.svg">
> 
> 
> I'll keep the old icons around for now, maybe with some small internal modifications so they can be updated easily later.
> 
> One thing I'd like to note, too, is that I found the name `open.svg` for the globe icon somewhat confusing

I've revised the missing icons. Now all icons should be 32x32 svgs :)
