### ISSUE TITLE
All localization is broken

### ISSUE THREAD

**Issue by arielitovsky** [inovex/scrumlr.io#4031]
### The problem

When you visit the homepage, none of the buttons or copy is localized

### Browser

Chrome Version 122.0.6261.129 (arm64)

### Steps to reproduce the behavior

1. Go to https://scrumlr.io/
2. Notice that none of the buttons of copy is localized

### Screenshots

<img width="1510" alt="image" src="https://github.com/inovex/scrumlr.io/assets/662807/141ff1a4-38d0-4da8-81fd-8d4d62f63fc4">

**Comment by brandstetterm** [comment]
Hey, thank you for reporting that problem. We are already aware of that problem. It's probably because the location of our translation files changed from the previous to the current version and we have a caching issue. To fix it on your side, you could try to hard refresh Scrumlr in the browser (on Chrome: CTRL/CMD + Shift + R).

**Comment by brandstetterm** [comment]
I think I've found the problem and developled a fix for it. The reason for this should have been an outdated main.js which has been pulled from our service worker. I've developed a fix in #4014 which self-destructs the service worker. On my local reproduction, it fixed the problem. I hope it also does on our prod deployment.

**Comment by brandstetterm** [comment]
Hey @arielitovsky, the problem should be resolved now. We've made some changes and deployed them as a test on https://scrumlr.io. If you still encounter issues (after some reloads perhaps), you can reopen this issue 😃
