### ISSUE TITLE
Login: "Securecookie: hash key is not set"

### ISSUE THREAD

**Issue by SelinaBuff** [inovex/scrumlr.io#4685]
# Error message when logging in with Google

### Description:
When I try to log in with Google, I encounter the following error message: "securecookie: hash key is not set". Please investigate and resolve this issue.

### Browser

Chrome

### Screenshots

![Image](https://github.com/user-attachments/assets/085c933d-d937-4d13-801f-d6035881430b)

**Comment by Schwehn42** [comment]
FIXED – The problem was a side-effect caused from importing `gorillaSessions`, which lead to the cookie store being overridden – therefore requiring `SESSION_SECRET` being set. We should add this to the documentation to prevent future problems and as a heads up for people self-hosting scrumlr. See #4697
